"""
AI Detector
Today's challenge is inspired by the release of ChatGPT on November 30, 2022.

Given a string of one or more sentences, determine if it was likely generated by AI using the following rules:
It contains two or more dashes (-).
It contains two or more sets of parenthesis (()). Text can be within the parenthesis.
It contains three or more words with 7 or more letters.
Words are separated by a single space and only consist of letters (A-Z). Don't include punctuation or other non-letters
as part of a word.

If the given sentence meets any of the rules above, return "AI", otherwise, return "Human".

1. detect_ai("The quick brown fox jumped over the lazy dog.") should return "Human".
2. detect_ai("The hypersonic brown fox - jumped (over) the lazy dog.") should return "Human".
3. detect_ai("Yes - you're right! I made a mistake there - let me try again.") should return "AI".
4. detect_ai("The extraordinary students were studying vivaciously.") should return "AI".
5. detect_ai("The (excited) student was (coding) in the library.") should return "AI".
"""

def detect_ai(text: str) -> str:
    parenthesis_threshold: bool = text.count("(") >= 2 and text.count(")") >= 2
    dash_threshold: bool = text.count("-") >= 2

    long_words: list[str] = []

    for word in text.split():
        cleaned_word = "".join([char for char in word if char.isalpha()])

        if len(cleaned_word) >= 7:
            long_words.append(cleaned_word)

    word_length: bool = len(long_words) >= 3

    if any((parenthesis_threshold, dash_threshold, word_length)):
        return "AI"

    return "Human"


print(detect_ai("The quick brown fox jumped over the lazy dog."))
print(detect_ai("The hypersonic brown fox - jumped (over) the lazy dog."))
print(detect_ai("Yes - you're right! I made a mistake there - let me try again."))
print(detect_ai("The extraordinary students were studying vivaciously."))
print(detect_ai("The (excited) student was (coding) in the library."))
